services:
  mailpit:
    image: axllent/mailpit:v1.18
    environment:
      - MP_DATA_FILE=/data/mailpit.db
    ports:
      - "8025:8025"
    volumes:
      - ./data/mailpit:/data
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
    ports:
      - "3306:3306"
    volumes:
      - ./data/db:/var/lib/mysql
  mysql-import:
    image: mysql:8
    depends_on:
      - mysql
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
    command: >
      /bin/sh -c '
      chmod +x ./wp-init/import-db.sh && ./wp-init/import-db.sh
      '
    volumes:
      - ./data/db:/var/lib/mysql
      - ./wp-init:/wp-init
      - ./restore:/etc/wp-dev-kit/restore
      - ./data/clidata:/etc/clidata
  phpmyadmin:
    image: phpmyadmin:5
    depends_on:
      - mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: mysql
    ports:
      - "8001:80"
  wordpress:
    image: wordpress:6.5.4-apache
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: db
      WORDPRESS_DEBUG: 0
    ports:
      - "8000:80"
    volumes:
      - ./data/wp:/var/www/html
      - ./theme:/var/www/html/wp-content/themes/wp-dev-kit-theme
#      - ./wp-starter-plugin:/var/www/html/wp-content/plugins/wp-starter-plugin
      - ./config/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
  # https://stackoverflow.com/questions/50999848/how-to-run-wp-cli-in-docker-compose-yml
#  wordpress-cli:
#    depends_on:
#      - mysql
#      - wordpress
#    image: wordpress:cli
#    environment:
#      WORDPRESS_DB_HOST: mysql
#      WORDPRESS_DB_USER: root
#      WORDPRESS_DB_PASSWORD: root
#      WORDPRESS_DB_NAME: wp_starter
#      SITE_ROOT_URL: http://localhost:8000
#      SITE_TITLE: WP Starter
#      ADMIN_USERNAME: user
#      ADMIN_PASSWORD: pass
#      ADMIN_EMAIL: info@ducode.org
#    user: root
#    restart: on-failure
#    command: >
#      /bin/sh -c '
#      chmod +x /wp-init/wp-init.sh && /wp-init/wp-init.sh
#      '
#    volumes:
#      - wp_data:/var/www/html
#      - ./src:/var/www/html/wp-content/themes/wp-starter
#      - ./wp-starter-plugin:/var/www/html/wp-content/plugins/wp-starter-plugin
#      - ./wp-init:/wp-init
#      - cli_data:/etc/clidata
#      - ./restore:/etc/wp-starter/restore
volumes:
  cli_data: